### ISSUE TITLE
[Bug]: FLUX preset crashed SimpleSDXL

### ISSUE THREAD

**Issue by nyukers** [metercai/SimpleSDXL#103]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [ ] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

FLUX preset crashed SimpleSDXL

### Steps to reproduce the problem

1. Select FLUX preset
2. SimpleSDXL crashed

### What should have happened?

SimpleSDXL is working good

### Where are you running Fooocus?

Locally

### What operating system are you using?

Windows 10 22H2

### Console logs

```Shell
Loaded preset: D:\FooocusSDXL2\SimpleSDXL2\SimpleSDXL\presets\Flux.json
[Comfyd] Comfyd freeing!
Downloading: "https://huggingface.co/metercai/SimpleSDXL2/resolve/main/flux1/ae.safetensors" to D:\models\vae\ae.safetensors
正在下载模型文件: "https://huggingface.co/metercai/SimpleSDXL2/resolve/main/flux1/ae.safetensors"。如果速度慢，可终止运行，自行 用工具下载后保存到: D:\models\vae\ae.safetensors，然后重启应用。

Traceback (most recent call last):
  File "D:\FooocusSDXL2\SimpleSDXL2\python_embeded\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\FooocusSDXL2\SimpleSDXL2\python_embeded\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\FooocusSDXL2\SimpleSDXL2\python_embeded\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\FooocusSDXL2\SimpleSDXL2\python_embeded\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\FooocusSDXL2\SimpleSDXL2\python_embeded\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "D:\FooocusSDXL2\SimpleSDXL2\python_embeded\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "D:\FooocusSDXL2\SimpleSDXL2\python_embeded\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\FooocusSDXL2\SimpleSDXL2\SimpleSDXL\enhanced\topbar.py", line 418, in reset_layout_params
    download_models(default_model, previous_default_models, checkpoint_downloads, embeddings_downloads, lora_downloads, vae_downloads)
  File "D:\FooocusSDXL2\SimpleSDXL2\SimpleSDXL\enhanced\topbar.py", line 457, in download_models
    load_file_from_url(url=url, model_dir=config.path_vae, file_name=file_name)
  File "D:\FooocusSDXL2\SimpleSDXL2\SimpleSDXL\modules\model_loader.py", line 74, in load_file_from_url
    download_url_to_file(url, cached_file, progress=progress)
  File "D:\FooocusSDXL2\SimpleSDXL2\python_embeded\lib\site-packages\torch\hub.py", line 622, in download_url_to_file
    u = urlopen(req)
  File "urllib\request.py", line 216, in urlopen
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 634, in http_response
  File "urllib\request.py", line 563, in error
  File "urllib\request.py", line 496, in _call_chain
  File "urllib\request.py", line 643, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
```

### Additional information

SimpleSDXL version: v20240916.fc97754

**Comment by metercai** [comment]
可以从这里下载，https://huggingface.co/metercai/SimpleSDXL2/resolve/main/SimpleModels/vae/ae.safetensors
并放到对应的目录下：D:\models\vae\

**Comment by nyukers** [comment]
> 可以从这里下载，https://huggingface.co/metercai/SimpleSDXL2/resolve/main/SimpleModels/vae/ae.safetensors 并放到对应的目录下：D:\models\vae\
You are well done, thanks.
Your SimpleSDXL has 2 Flux **presets** and 10 Flux **workflows**. When are those workflows used?

**Comment by metercai** [comment]
已改目录
