### ISSUE TITLE
在colab运行

### ISSUE THREAD

**Issue by Van-wise** [metercai/SimpleSDXL#13]
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/hashlib.py", line 160, in __hash_new
    return _hashlib.new(name, data, **kwargs)
ValueError: [digital envelope routines] unsupported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/SimpleSDXL/launch.py", line 107, in <module>
    from webui import *
  File "/content/SimpleSDXL/webui.py", line 23, in <module>
    import enhanced.gallery as gallery_util
  File "/content/SimpleSDXL/enhanced/gallery.py", line 8, in <module>
    import enhanced.topbar as topbar
  File "/content/SimpleSDXL/enhanced/topbar.py", line 290, in <module>
    token_did.init_local_did(f'SimpleSDXL_User')
  File "/content/SimpleSDXL/enhanced/token_did.py", line 58, in init_local_did
    DID = base58.b58encode_check(hashlib.new('ripemd160', claim_sha256).digest()).decode('utf-8')
  File "/usr/lib/python3.10/hashlib.py", line 166, in __hash_new
    return __get_builtin_constructor(name)(data)
  File "/usr/lib/python3.10/hashlib.py", line 123, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type ripemd160

```
我是使用https://colab.research.google.com/github/Van-wise/sd-colab/blob/main/fooocus/fcoooucs.ipynb 笔记。

**Comment by metercai** [comment]
从日志输出看，可能是环境里面的hashlib版本不对，不支持ripemd160哈希算法。我没有colab的环境和使用经验，不知道怎么改，可以问问其他对colab有经验的人。

**Comment by metercai** [comment]
查了一下，hashlib的ripemd160是由openssl支撑的，需要确认你的colab环境中是否安装好了openssl。

**Comment by Van-wise** [comment]
已修复，我把 enhanced/token_did.py 中的
`DID = base58.b58encode_check(hashlib.new('ripemd160', claim_sha256).digest()).decode('utf-8')`
修改为
`DID = base58.b58encode_check(hashlib.new('sha256', claim_sha256).digest()).decode('utf-8')`

DID = base58.b58encode_check(hashlib.new('sha256', claim_sha256).digest()).decode('utf-8')
print(f'[TokenDID] Generated local_did: "{DID}"')
