### ISSUE TITLE
更新了1月6日的版本，出现了报错

### ISSUE THREAD

**Issue by xiaoyan1995** [metercai/SimpleSDXL#21]
报错内容如下：
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "H:\ai\Fooocus_win64_2-1-791\mogai\SimpleSDXL_win64_in\SimpleSDXL\modules\async_worker.py", line 25, in worker
    import modules.default_pipeline as pipeline
  File "H:\ai\Fooocus_win64_2-1-791\mogai\SimpleSDXL_win64_in\SimpleSDXL\modules\default_pipeline.py", line 1, in <module>
    import modules.core as core
  File "H:\ai\Fooocus_win64_2-1-791\mogai\SimpleSDXL_win64_in\SimpleSDXL\modules\core.py", line 1, in <module>
    from modules.patch import patch_all
  File "H:\ai\Fooocus_win64_2-1-791\mogai\SimpleSDXL_win64_in\SimpleSDXL\modules\patch.py", line 11, in <module>
    import ldm_patched.modules.sd1_clip
  File "H:\ai\Fooocus_win64_2-1-791\mogai\SimpleSDXL_win64_in\SimpleSDXL\ldm_patched\modules\sd1_clip.py", line 3, in <module>
    from transformers import CLIPTokenizer
ImportError: cannot import name 'CLIPTokenizer' from 'transformers' (H:\ai\Fooocus_win64_2-1-791\mogai\SimpleSDXL_win64_in\python_embeded\lib\site-packages\transformers\__init__.py)

**Comment by Van-wise** [comment]
/content/SimpleSDXL/ldm_patched/modules/sd1_clip.py
第三行,修改为
from transformers.models.clip import CLIPTokenizer
