### ISSUE TITLE
新版本点击生成预制包出错： NameError: name 'url' is not defined

### ISSUE THREAD

**Issue by shengli963** [metercai/SimpleSDXL#23]
Traceback (most recent call last):
  File "C:\AIGC\SD\FooocsSimple\SimpleSDXL_win64_2-1-822\python_embeded\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\AIGC\SD\FooocsSimple\SimpleSDXL_win64_2-1-822\python_embeded\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\AIGC\SD\FooocsSimple\SimpleSDXL_win64_2-1-822\python_embeded\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\AIGC\SD\FooocsSimple\SimpleSDXL_win64_2-1-822\python_embeded\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\AIGC\SD\FooocsSimple\SimpleSDXL_win64_2-1-822\python_embeded\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\AIGC\SD\FooocsSimple\SimpleSDXL_win64_2-1-822\python_embeded\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\AIGC\SD\FooocsSimple\SimpleSDXL_win64_2-1-822\python_embeded\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\AIGC\SD\FooocsSimple\SimpleSDXL_win64_2-1-822\SimpleSDXL\enhanced\toolbox.py", line 350, in save_preset
    if url:
NameError: name 'url' is not defined

**Comment by metercai** [comment]
漏网之鱼，thx！

**Comment by metercai** [comment]
已修订，并同步主线的修订
