### ISSUE TITLE
[Bug]: ATI：未找到命令 when executing commmand “lspci | grep VGA | grep -E AMD|ATI” 

### ISSUE THREAD

**Issue by flyingti** [metercai/SimpleSDXL#48]
### Checklist

- [ ] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [ ] The issue exists on a clean installation of Fooocus
- [ ] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

show error: ATI：未找到命令 when executing commmand “lspci | grep VGA | grep -E AMD|ATI”  

### Steps to reproduce the problem

1.my computer environment is Ubuntu 22.04.4 LTS and AMD Radeon RX 6800/6800 XT;
2.According to installation of Linux:
git clone https://github.com/metercai/SimpleSDXL.git
cd SimpleSDXL
conda env create -f environment.yaml
conda activate fooocus
pip install -r requirements_versions.txt 
python entry_with_update.py
3.show information & error:
Python 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0]
Fooocus version: 2.4.3
SimpleSDXL version: v20240528.6a43e92
Comfy Backend cloned.
Comfy Backend 30abc32 update check complete.
Checking ...
Failed to run command: sh ["-c", "lspci | grep VGA | grep NVIDIA"], error: 
Failed to run command: sh ["-c", "lspci | grep VGA | grep -E AMD|ATI"], error: sh: 1: ATI: not found
......

### What should have happened?

Final, simplesdxl don't start sucessfully.

if using Double quotation mark of AMD|ATI, such as lspci | grep VGA | grep -E "AMD|ATI", the command is right and no error information.

### Where are you running Fooocus?

None

### Console logs

```Shell
SimpleSDXL: Already up-to-date, 6a43e92
SimpleSDXL: Update succeeded.
[System ARGV] ['entry_with_update.py', '--preset', 'realistic']
Python 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0]
Fooocus version: 2.4.3
SimpleSDXL version: v20240528.6a43e92
Comfy Backend 30abc32 update check complete.
Checking ...
Failed to run command: sh ["-c", "lspci | grep VGA | grep NVIDIA"], error: 
Failed to run command: sh ["-c", "lspci | grep VGA | grep -E AMD|ATI"], error: sh: 1: ATI: not found

Load config data from /media/lzg/AI/AI/ubuntun/SimpleSDXL/config.txt.
Loaded preset: /media/lzg/AI/AI/ubuntun/SimpleSDXL/presets/realistic.json
[Cleanup] Attempting to delete content of temp dir /tmp/fooocus
[Cleanup] Cleanup successful
Traceback (most recent call last):
  File "/media/lzg/AI/AI/ubuntun/SimpleSDXL/entry_with_update.py", line 86, in <module>
    from launch import *
  File "/media/lzg/AI/AI/ubuntun/SimpleSDXL/launch.py", line 214, in <module>
    from webui import *
  File "/media/lzg/AI/AI/ubuntun/SimpleSDXL/webui.py", line 10, in <module>
    import modules.async_worker as worker
  File "/media/lzg/AI/AI/ubuntun/SimpleSDXL/modules/async_worker.py", line 3, in <module>
    from modules.patch import PatchSettings, patch_settings, patch_all
  File "/media/lzg/AI/AI/ubuntun/SimpleSDXL/modules/patch.py", line 5, in <module>
    import ldm_patched.modules.model_base
  File "/media/lzg/AI/AI/ubuntun/SimpleSDXL/ldm_patched/modules/model_base.py", line 2, in <module>
    from ldm_patched.ldm.modules.diffusionmodules.openaimodel import UNetModel, Timestep
  File "/media/lzg/AI/AI/ubuntun/SimpleSDXL/ldm_patched/ldm/modules/diffusionmodules/openaimodel.py", line 15, in <module>
    from ..attention import SpatialTransformer, SpatialVideoTransformer, default
  File "/media/lzg/AI/AI/ubuntun/SimpleSDXL/ldm_patched/ldm/modules/attention.py", line 9, in <module>
    from .sub_quadratic_attention import efficient_dot_product_attention
  File "/media/lzg/AI/AI/ubuntun/SimpleSDXL/ldm_patched/ldm/modules/sub_quadratic_attention.py", line 27, in <module>
    from ldm_patched.modules import model_management
  File "/media/lzg/AI/AI/ubuntun/SimpleSDXL/ldm_patched/modules/model_management.py", line 121, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "/media/lzg/AI/AI/ubuntun/SimpleSDXL/ldm_patched/modules/model_management.py", line 90, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "/media/lzg/Game/miniconda3/envs/simplesdxl/lib/python3.10/site-packages/torch/cuda/__init__.py", line 778, in current_device
    _lazy_init()
  File "/media/lzg/Game/miniconda3/envs/simplesdxl/lib/python3.10/site-packages/torch/cuda/__init__.py", line 293, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
.......
```

### Additional information

lspci | grep VGA | grep -E "AMD|ATI"
03:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] (rev c1)

**Comment by metercai** [comment]
we are resolving compatibility issues with AMD, you can add a QQ group: 938075852 to verify and test it
