### ISSUE TITLE
[Bug]: 使用【参数提取】功能，出现错误。

### ISSUE THREAD

**Issue by hpwater** [metercai/SimpleSDXL#49]
### Checklist

- [ ] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [ ] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

使用【参数提取】功能，出现错误。

### Steps to reproduce the problem

1、图像输入
2、参数提取
3、上传图片
4、提取图片生成参数重置环境

### What should have happened?

获取体魄生成参数以及相关的配置

### What browsers do you use to access Fooocus?

Microsoft Edge

### Where are you running Fooocus?

Locally

### Console logs

```Shell
Traceback (most recent call last):
  File "D:\Aools\SimpleSDXL\python_embeded\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\Aools\SimpleSDXL\python_embeded\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\Aools\SimpleSDXL\python_embeded\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\Aools\SimpleSDXL\python_embeded\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\Aools\SimpleSDXL\python_embeded\lib\site-packages\anyio\_backends\_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "D:\Aools\SimpleSDXL\python_embeded\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "D:\Aools\SimpleSDXL\python_embeded\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\Aools\SimpleSDXL\SimpleSDXL\webui.py", line 936, in trigger_metadata_import
    parsed_parameters = metadata_parser.to_json(parameters)
  File "D:\Aools\SimpleSDXL\SimpleSDXL\modules\meta_parser.py", line 631, in to_json
    if modules.config.sdxl_lcm_lora in lora_filenames:
AttributeError: module 'modules.config' has no attribute 'sdxl_lcm_lora'
```

**Comment by metercai** [comment]
升级新的版本的，没有这个问题

**Comment by hpwater** [comment]
升级新新版本后，运行run_SimpleSDXL_without_update，出现以下错误。

Traceback (most recent call last):
  File "D:\Aools\SimpleSDXL\SimpleSDXL\launch.py", line 205, in <module>
    from modules import config
  File "D:\Aools\SimpleSDXL\SimpleSDXL\modules\config.py", line 8, in <module>
    import shared
  File "D:\Aools\SimpleSDXL\SimpleSDXL\shared.py", line 2, in <module>
    import launch
  File "D:\Aools\SimpleSDXL\SimpleSDXL\launch.py", line 207, in <module>
    os.environ['GRADIO_TEMP_DIR'] = config.temp_path
AttributeError: partially initialized module 'modules.config' has no attribute 'temp_path' (most likely due to a circular import)
All done.
请按任意键继续. . .
