### ISSUE TITLE
[Bug]: 0731版本 cannot import name 'HunyuanDiTPipeline' from 'diffusers' 

### ISSUE THREAD

**Issue by zjs0813** [metercai/SimpleSDXL#56]
### Checklist

- [ ] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [ ] The issue exists on a clean installation of Fooocus
- [ ] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

       --------------------------------------

### Steps to reproduce the problem

开始安装挺好的，第二天就出问题了，装了几次还是这个问题.

### What should have happened?

       --------------------------------------

### Where are you running Fooocus?

None

### What operating system are you using?

win11

### Console logs

```Shell
SimpleSDXL: Already up-to-date, feea3f1
[System ARGV] ['SimpleSDXL\\entry_with_update.py', '--models-root', '../../SimpleModels', '--output-path', '../../outputs']
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Fooocus version: 2.5.2
Comfy version: 897325c
SimpleSDXL version: v20240731.feea3f1
Checking ...
[SimpleAI] GPU: NVIDIA GeForce RTX 4070 Laptop GPU, RAM: 32471MB, SWAP: 36687MB, VRAM: 8188MB, DiskFree: 9284MB
[SimpleAI] local_did/本地身份ID: 4W9E9vi3vww4YELHxWmN5Yot5mYt
Load config data from E:\SimpleAI\SimpleSDXL2_win\SimpleSDXL\config.txt.
Loaded preset: E:\SimpleAI\SimpleSDXL2_win\SimpleSDXL\presets\default.json
The path_models_root: E:\SimpleAI\SimpleModels
The path_output: E:\SimpleAI\outputs
Total VRAM 8188 MB, total RAM 32472 MB
xformers version: 0.0.26
Set vram state to: NORMAL_VRAM
Always offload VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 Laptop GPU : native
VAE dtype: torch.bfloat16
[SimpleAI] The path of models_info file: E:\SimpleAI\SimpleModels\models_info.json
[Cleanup] Attempting to delete content of temp dir C:\Users\Administrator\AppData\Local\Temp\fooocus
[Cleanup] Cleanup successful
Using xformers cross attention
Refiner unloaded.
model_type EPS
UNet ADM Dimension 2816
Traceback (most recent call last):
  File "E:\SimpleAI\SimpleSDXL2_win\SimpleSDXL\entry_with_update.py", line 90, in <module>
    from launch import *
  File "E:\SimpleAI\SimpleSDXL2_win\SimpleSDXL\launch.py", line 311, in <module>
    from webui import *
  File "E:\SimpleAI\SimpleSDXL2_win\SimpleSDXL\webui.py", line 23, in <module>
    from modules.private_logger import get_current_html_path
  File "E:\SimpleAI\SimpleSDXL2_win\SimpleSDXL\modules\private_logger.py", line 8, in <module>
    import enhanced.toolbox as toolbox
  File "E:\SimpleAI\SimpleSDXL2_win\SimpleSDXL\enhanced\toolbox.py", line 11, in <module>
    import enhanced.topbar as topbar
  File "E:\SimpleAI\SimpleSDXL2_win\SimpleSDXL\enhanced\topbar.py", line 20, in <module>
    import enhanced.hydit_task as hydit_task
  File "E:\SimpleAI\SimpleSDXL2_win\SimpleSDXL\enhanced\hydit_task.py", line 17, in <module>
    from diffusers import HunyuanDiTPipeline, DDPMScheduler, DDIMScheduler, DPMSolverMultistepScheduler
ImportError: cannot import name 'HunyuanDiTPipeline' from 'diffusers' (E:\SimpleAI\SimpleSDXL2_win\python_embeded\lib\site-packages\diffusers\__init__.py)
All done.
```

**Comment by metercai** [comment]
你这个错误无法复现，也没有第二个人反馈这个错误。从输出的日志来看，是diffusers的版本不对，无法导入HunyuanDiTPipeline这类。
解决办法：
1，请自查一下运行环境的diffusers版本号，自己修正环境。
2，等后续的新版本，hydit_task和HunyuanDiTPipeline会被去掉，不用这种方式了。
