### ISSUE TITLE
出现同一个错误，提参重生和生成预置包

### ISSUE THREAD

**Issue by xhoxye** [metercai/SimpleSDXL#8]
**Read Troubleshoot**

[x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

**Describe the problem**

**Full Console Log**
Traceback (most recent call last):
  File "E:\AI\Fooocus\fooocuspy\python_embeded\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\AI\Fooocus\fooocuspy\python_embeded\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "E:\AI\Fooocus\fooocuspy\python_embeded\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\AI\Fooocus\fooocuspy\python_embeded\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\AI\Fooocus\fooocuspy\python_embeded\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\AI\Fooocus\fooocuspy\python_embeded\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\AI\Fooocus\fooocuspy\python_embeded\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "E:\AI\Fooocus\fooocuspy\SimpleSDXL\enhanced\gallery.py", line 233, in toggle_note_box_preset
    if i<2 and topbar.models_info["checkpoints/"+checklist[i]]["url"] is None:
KeyError: 'checkpoints/juggernautXL_version6Rundiffusion.safetensors'

![QQ截图20231212193726](https://github.com/metercai/SimpleSDXL/assets/129571231/65f1552a-c2c6-400f-9cb1-b1d7a692af30)

**Comment by metercai** [comment]
刚更新，试试新版本

**Comment by xhoxye** [comment]
是不是因为这个？
![image](https://github.com/metercai/SimpleSDXL/assets/129571231/8d642d78-3c23-40b1-b8bd-576f9f3a33a8)

**Comment by xhoxye** [comment]
可以了
![QQ截图20231212211808](https://github.com/metercai/SimpleSDXL/assets/129571231/3b0d2cfc-04c4-4b80-9b7d-99e3567f74b7)
![QQ截图20231212211833](https://github.com/metercai/SimpleSDXL/assets/129571231/ab698866-8faf-4814-85cf-8434f2a1ff6b)

**Comment by metercai** [comment]
1，生成预置包出错的后台提示是什么？
2，在启动日志里面看看是否能找到这一行：[Topbar] Total time for model file hash xxx

**Comment by xhoxye** [comment]
生成配置包，没有反应，后台没有提示，点击没有反应
启动日志在上面一个回复里有，是这个
[Topbar] Total time for model file hash 0.00 seconds

**Comment by metercai** [comment]
看到了，更换了兼容性更好的写法，再试试看

**Comment by metercai** [comment]
主线新版本更新了log.html格式，同步适配了新老格式，可以帮忙验证一下。
