### ISSUE TITLE
[Bug]: UI loading OK, cant change the language, and cant create images

### ISSUE THREAD

**Issue by vampireprincess** [metercai/SimpleSDXL#89]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [ ] The issue exists on a clean installation of Fooocus
- [ ] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Hi SimpleSDXL team,

I installed your package and the required model packages, I downloaded the "Flux1 low memory package 23G." 
After installation, the interface automatically loaded, but I can't change it to English. Although I can click on the language option, nothing happens when I try to switch. The only way I can view the interface in English is by right-clicking in Chrome and selecting "Translate to English."

When changing the presets, I can see they are working since the correct models load for Juggernaut, Flux dev, and Flux Schnell. If I click on a preset for a model I don’t have, it automatically starts downloading it, which seems to indicate that part is functioning as expected.

Additionally, when I try to create outputs using either Juggernaut or Flux, I enter my prompt and start the generation. The interface indicates that the generation process has begun, but in the command prompt, nothing seems to happen. The last line repeatedly says, "Starting Comfyd server!" but no further progress occurs.

Could you provide any guidance on these issues?

Thank you for your help!
![ScreenShot_20241027224046](https://github.com/user-attachments/assets/fd619bcc-abec-4974-a34c-5629402c6894)

### Steps to reproduce the problem

1. started the UI
2. changing language to En (not working)
3. in Juggernaut writing a prompt Penguin clicking on generate button (nothing happening)

### What should have happened?

The language should change to english, and I should generate an image.

### What browsers do you use to access Fooocus?

Mozilla Firefox

### Where are you running Fooocus?

Locally

### Console logs

```Shell
[System ARGV] ['SimpleSDXL\\entry_without_update.py', '--models-root', '../../SimpleModels', '--output-path', '../../outputs']
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Fooocus version: 2.5.5
Comfy version: 1dba801
SimpleSDXL version: v20240916.fc97754
Checking ...
[SimpleAI] GPU: NVIDIA GeForce RTX 3070, RAM: 65450MB, SWAP: 9728MB, VRAM: 8192MB, DiskFree: 100077MB, CUDA: 12.6
[SimpleAI] local_did/本地身份ID: 2GKTSVVE3p8QmwWdqHkXsQEUiSF8
Load config data from F:\SimpleAI\SimpleSDXL2_win_0916\SimpleSDXL\config.txt.
Loaded preset: F:\SimpleAI\SimpleSDXL2_win_0916\SimpleSDXL\presets\default.json
The path_models_root: F:\SimpleAI\SimpleModels
The path_output: F:\SimpleAI\outputs
Total VRAM 8192 MB, total RAM 65451 MB
xformers version: 0.0.27
Set vram state to: NORMAL_VRAM
Always offload VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 : native
VAE dtype: torch.bfloat16
[Cleanup] Attempting to delete content of temp dir C:\Users\user\AppData\Local\Temp\fooocus
[Cleanup] Cleanup successful
Checking file is not exists / 检测到文件有缺失: F:\SimpleAI\SimpleModels\upscale_models\fooocus_upscaler_s409985e5.bin
[SimpleAI] 程序所需基础模型包有检测异常，未完全正确安装。请检查并正确安装后，再启动程序。
Env_ready_code: 2
Using xformers cross attention
Refiner unloaded.
model_type EPS
UNet ADM Dimension 2816
[Wildcards] Refresh and Load 27/27 wildcards: animal, bodytypes, buildings, chairs, color, containers, coverings, flora, flower, focus, foods, hairstyles, jobs, materials, minilocations, moods, nationality, objects, objectstohold, outfits, patterns, poses, rpg, shotsizes, space, timeperiods, vehicles.
[OneButtonPrompt] The customized module:OneButtonPrompt is initializing ...
Running on local URL:  http://192.168.1.6:8186

To create a public link, set `share=True` in `launch()`.
[Comfyd] Fix and patch for torch in windows
IMPORTANT: You are using gradio version 3.41.2, however version 4.44.1 is available, please upgrade.
--------
Using xformers attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using xformers attention in VAE
extra {'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection'}
left over keys: dict_keys(['cond_stage_model.clip_l.transformer.text_model.embeddings.position_ids'])
Base model loaded: F:\SimpleAI\SimpleModels\checkpoints\juggernautXL_juggXIByRundiffusion.safetensors
VAE loaded: None
Request to load LoRAs [('sd_xl_offset_example-lora_1.0.safetensors', 0.1)] for model [F:\SimpleAI\SimpleModels\checkpoints\juggernautXL_juggXIByRundiffusion.safetensors].
Loaded LoRA [F:\SimpleAI\SimpleModels\loras\sd_xl_offset_example-lora_1.0.safetensors] for UNet [F:\SimpleAI\SimpleModels\checkpoints\juggernautXL_juggXIByRundiffusion.safetensors] with 788 keys at weight 0.1.
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "F:\SimpleAI\SimpleSDXL2_win_0916\SimpleSDXL\modules\async_worker.py", line 229, in worker
    import modules.default_pipeline as pipeline
  File "F:\SimpleAI\SimpleSDXL2_win_0916\SimpleSDXL\modules\default_pipeline.py", line 296, in <module>
    refresh_everything(
  File "F:\SimpleAI\SimpleSDXL2_win_0916\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\SimpleAI\SimpleSDXL2_win_0916\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\SimpleAI\SimpleSDXL2_win_0916\SimpleSDXL\modules\default_pipeline.py", line 263, in refresh_everything
    final_expansion = FooocusExpansion()
  File "F:\SimpleAI\SimpleSDXL2_win_0916\SimpleSDXL\extras\expansion.py", line 39, in __init__
    self.tokenizer = AutoTokenizer.from_pretrained(path_fooocus_expansion)
  File "F:\SimpleAI\SimpleSDXL2_win_0916\python_embeded\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 846, in from_pretrained
    config = AutoConfig.from_pretrained(
  File "F:\SimpleAI\SimpleSDXL2_win_0916\python_embeded\lib\site-packages\transformers\models\auto\configuration_auto.py", line 965, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "F:\SimpleAI\SimpleSDXL2_win_0916\python_embeded\lib\site-packages\transformers\configuration_utils.py", line 632, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "F:\SimpleAI\SimpleSDXL2_win_0916\python_embeded\lib\site-packages\transformers\configuration_utils.py", line 689, in _get_config_dict
    resolved_config_file = cached_file(
  File "F:\SimpleAI\SimpleSDXL2_win_0916\python_embeded\lib\site-packages\transformers\utils\hub.py", line 373, in cached_file
    raise EnvironmentError(
OSError: F:\SimpleAI\SimpleModels\prompt_expansion\fooocus_expansion does not appear to have a file named config.json. Checkout 'https://huggingface.co/F:\SimpleAI\SimpleModels\prompt_expansion\fooocus_expansion/tree/None' for available files.
[Topbar] No accept-language in request.headers:{'host': '192.168.1.6:8186', 'connection': 'Upgrade', 'pragma': 'no-cache', 'cache-control': 'no-cache', 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36', 'upgrade': 'websocket', 'origin': 'http://192.168.1.6:8186', 'sec-websocket-version': '13', 'accept-encoding': 'gzip, deflate', 'accept-language': 'en-US,en;q=0.9', 'cookie': '_ga=GA1.1.1758775571.1728148968; _ga_R1FN4KJKJH=GS1.1.1728572685.2.1.1728573422.0.0.0', 'sec-websocket-key': '9Mg7mICJlRAB015blxFSSg==', 'sec-websocket-extensions': 'permessage-deflate; client_max_window_bits'}
[Gallery] Refresh_output_catalog: A total of 0 images and 0 pages, displaying the latest 0 pages.
[Comfyd] Disabling smart memory management
[Comfyd] Device: cuda:0 NVIDIA GeForce RTX 3070 : cudaMallocAsync
[Comfyd] [Prompt Server] web root: F:\SimpleAI\SimpleSDXL2_win_0916\SimpleSDXL\comfy\web
[Comfyd] Prestartup times for custom nodes:
[Comfyd]       0.0 seconds: F:\SimpleAI\SimpleSDXL2_win_0916\SimpleSDXL\comfy\custom_nodes\rgthree-comfy
[Comfyd]       0.0 seconds: F:\SimpleAI\SimpleSDXL2_win_0916\SimpleSDXL\comfy\custom_nodes\ComfyUI-Easy-Use
[ComfyUI-Easy-Use] server: v1.2.2 Loaded
[ComfyUI-Easy-Use] web root: F:\SimpleAI\SimpleSDXL2_win_0916\SimpleSDXL\comfy\custom_nodes\ComfyUI-Easy-Use\web_version/v2 Loaded
[Comfyd] Disabling smart memory management
[Comfyd] Device: cuda:0 NVIDIA GeForce RTX 3070 : cudaMallocAsync
[comfyui_controlnet_aux] | INFO -> Using ckpts path: F:\SimpleAI\SimpleModels\checkpoints
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
F:\SimpleAI\SimpleSDXL2_win_0916\SimpleSDXL\comfy\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py:26: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")
[Comfyd] A new version of Albumentations is available: 1.4.20 (you have 1.4.7). Upgrade using: pip install --upgrade albumentations
Nvidia APEX normalization not installed, using PyTorch LayerNorm

[rgthree] Loaded 42 extraordinary nodes.
[rgthree] NOTE: Will NOT use rgthree's optimized recursive execution as ComfyUI has changed.

[Comfyd] Import times for custom nodes:
[Comfyd]    0.0 seconds: F:\SimpleAI\SimpleSDXL2_win_0916\SimpleSDXL\comfy\custom_nodes\websocket_image_save.py
[Comfyd]    0.0 seconds: F:\SimpleAI\SimpleSDXL2_win_0916\SimpleSDXL\comfy\custom_nodes\AIGODLIKE-COMFYUI-TRANSLATION
[Comfyd]    0.0 seconds: F:\SimpleAI\SimpleSDXL2_win_0916\SimpleSDXL\comfy\custom_nodes\simpleai-seamless-tiled
[Comfyd]    0.0 seconds: F:\SimpleAI\SimpleSDXL2_win_0916\SimpleSDXL\comfy\custom_nodes\ComfyUI-FluxExt-MZ
[Comfyd]    0.0 seconds: F:\SimpleAI\SimpleSDXL2_win_0916\SimpleSDXL\comfy\custom_nodes\ComfyUI_Noise
[Comfyd]    0.0 seconds: F:\SimpleAI\SimpleSDXL2_win_0916\SimpleSDXL\comfy\custom_nodes\ComfyUI_IPAdapter_plus
[Comfyd]    0.0 seconds: F:\SimpleAI\SimpleSDXL2_win_0916\SimpleSDXL\comfy\custom_nodes\ComfyUI-layerdiffuse
[Comfyd]    0.0 seconds: F:\SimpleAI\SimpleSDXL2_win_0916\SimpleSDXL\comfy\custom_nodes\ComfyUI_essentials
[Comfyd]    0.0 seconds: F:\SimpleAI\SimpleSDXL2_win_0916\SimpleSDXL\comfy\custom_nodes\ComfyUI-Advanced-ControlNet
[Comfyd]    0.0 seconds: F:\SimpleAI\SimpleSDXL2_win_0916\SimpleSDXL\comfy\custom_nodes\ComfyUI_UltimateSDUpscale
[Comfyd]    0.0 seconds: F:\SimpleAI\SimpleSDXL2_win_0916\SimpleSDXL\comfy\custom_nodes\ComfyUI-KJNodes
[Comfyd]    0.0 seconds: F:\SimpleAI\SimpleSDXL2_win_0916\SimpleSDXL\comfy\custom_nodes\x-flux-comfyui
[Comfyd]    0.0 seconds: F:\SimpleAI\SimpleSDXL2_win_0916\SimpleSDXL\comfy\custom_nodes\ComfyUI-GGUF
[Comfyd]    0.0 seconds: F:\SimpleAI\SimpleSDXL2_win_0916\SimpleSDXL\comfy\custom_nodes\ComfyUI_ExtraModels
[Comfyd]    0.0 seconds: F:\SimpleAI\SimpleSDXL2_win_0916\SimpleSDXL\comfy\custom_nodes\rgthree-comfy
[Comfyd]    0.0 seconds: F:\SimpleAI\SimpleSDXL2_win_0916\SimpleSDXL\comfy\custom_nodes\ComfyUI-Kolors-MZ
[Comfyd]    0.0 seconds: F:\SimpleAI\SimpleSDXL2_win_0916\SimpleSDXL\comfy\custom_nodes\ComfyUI_bitsandbytes_NF4
[Comfyd]    0.0 seconds: F:\SimpleAI\SimpleSDXL2_win_0916\SimpleSDXL\comfy\custom_nodes\ComfyUI-IC-Light
[Comfyd]    0.0 seconds: F:\SimpleAI\SimpleSDXL2_win_0916\SimpleSDXL\comfy\custom_nodes\ComfyUI-KwaiKolorsWrapper
[Comfyd]    0.1 seconds: F:\SimpleAI\SimpleSDXL2_win_0916\SimpleSDXL\comfy\custom_nodes\comfyui_controlnet_aux
[Comfyd]    0.1 seconds: F:\SimpleAI\SimpleSDXL2_win_0916\SimpleSDXL\comfy\custom_nodes\PuLID_ComfyUI
[Comfyd]    0.1 seconds: F:\SimpleAI\SimpleSDXL2_win_0916\SimpleSDXL\comfy\custom_nodes\ComfyUI-Easy-Use
[Comfyd]    0.1 seconds: F:\SimpleAI\SimpleSDXL2_win_0916\SimpleSDXL\comfy\custom_nodes\ComfyUI-BrushNet
[Comfyd]    0.6 seconds: F:\SimpleAI\SimpleSDXL2_win_0916\SimpleSDXL\comfy\custom_nodes\ComfyUI_InstantID
[Comfyd]    1.8 seconds: F:\SimpleAI\SimpleSDXL2_win_0916\SimpleSDXL\comfy\custom_nodes\ComfyUI-SUPIR
[Comfyd]
[Comfyd] Starting Comfyd server!
```

**Comment by DavidDragonsage** [comment]
@vampireprincess - what an appropriate name for the season!

I am not a member of the development team, but I am the owner of the Facebook Pure Fooocus group:
https://www.facebook.com/groups/fooocus
I think you will get a lot more help there. The content is viewable by anyone but you will need to join to be able to post.

The file you use to run SimpleSDXL, "run_SimpleSDXL.bat" should look something like this:

@echo off
python_embeded\python.exe -s SimpleSDXL\entry_with_update.py --models-root ../../SimpleModels --output-path E:/stable-diffusion-webui/outputs --language en
echo All done.
pause

Notice the "--language en" switch at the end of the second line. That will put you in English mode. Just add that with a text editor.

But also, it looks like the installation is faulty, and I notice that SimpleSDXL has not properly updated to the latest version. The installation instructions at this site are very confusing. In the Facebook Pure Fooocus group, see the "SimpleSDXL - The New Fooocus?" guide. currently Guide #11. The second article in that guide has an installation procedure that actually works.

I think I would delete or simply rename your current installation so that you can get a fresh start.

**Comment by vampireprincess** [comment]
@DavidDragonsage thank you very much for the answer I will join the mentioned group, and if I solve my issue, I will post it here. Happy Halloween David

**Comment by vampireprincess** [comment]
@DavidDragonsage, thank you so much! You were absolutely right—I needed to reinstall the Simple Model folder, and now it's working perfectly! ❤️

**Comment by DavidDragonsage** [comment]
Great news! 👍
